//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moe.La.Common.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumsLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumsLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moe.La.Common.Resources.Common.EnumsLocalization", typeof(EnumsLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزارة العدل.
        /// </summary>
        public static string a {
            get {
                return ResourceManager.GetString("a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبول طلب تغيير الباحث.
        /// </summary>
        public static string AcceptChangeResearcherRequest {
            get {
                return ResourceManager.GetString("AcceptChangeResearcherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتمد.
        /// </summary>
        public static string Accepted {
            get {
                return ResourceManager.GetString("Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستلمة للمراجعة.
        /// </summary>
        public static string AcceptedForReview {
            get {
                return ResourceManager.GetString("AcceptedForReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقبول من المستشار.
        /// </summary>
        public static string AcceptedFromConsultant {
            get {
                return ResourceManager.GetString("AcceptedFromConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مفعل.
        /// </summary>
        public static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة ملخص الجلسة.
        /// </summary>
        public static string AddHearingSummary {
            get {
                return ResourceManager.GetString("AddHearingSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مذكرة لجلسة.
        /// </summary>
        public static string AddLegalMemoToHearing {
            get {
                return ResourceManager.GetString("AddLegalMemoToHearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مذكرة اعتراضية لقضية .
        /// </summary>
        public static string AddObjectionLegalMemoToCase {
            get {
                return ResourceManager.GetString("AddObjectionLegalMemoToCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة طلب الاعتراض او الاكتفاء بالحكم.
        /// </summary>
        public static string AddObjectionPermitRequest {
            get {
                return ResourceManager.GetString("AddObjectionPermitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اداري.
        /// </summary>
        public static string Administrative {
            get {
                return ResourceManager.GetString("Administrative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ضد الوزارة.
        /// </summary>
        public static string Against {
            get {
                return ResourceManager.GetString("Against", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وكيل.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محكمة استئناف.
        /// </summary>
        public static string Appeal {
            get {
                return ResourceManager.GetString("Appeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استئناف.
        /// </summary>
        public static string Appealed {
            get {
                return ResourceManager.GetString("Appealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتمدة من رئيس اللجان.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسندة.
        /// </summary>
        public static string Assigned {
            get {
                return ResourceManager.GetString("Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاب إلحاقي.
        /// </summary>
        public static string AttachedLetter {
            get {
                return ResourceManager.GetString("AttachedLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكفوف اليد.
        /// </summary>
        public static string BlindHand {
            get {
                return ResourceManager.GetString("BlindHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قضية.
        /// </summary>
        public static string Case {
            get {
                return ResourceManager.GetString("Case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حكم القضية.
        /// </summary>
        public static string CaseJudgement {
            get {
                return ResourceManager.GetString("CaseJudgement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترك الدعوة من المدعى.
        /// </summary>
        public static string CaseLeaveByClaimant {
            get {
                return ResourceManager.GetString("CaseLeaveByClaimant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حكم.
        /// </summary>
        public static string CaseRule {
            get {
                return ResourceManager.GetString("CaseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصنفة.
        /// </summary>
        public static string Categorized {
            get {
                return ResourceManager.GetString("Categorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابن.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلقة.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قضية مغلقة.
        /// </summary>
        public static string ClosedCase {
            get {
                return ResourceManager.GetString("ClosedCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلقة 1.
        /// </summary>
        public static string ClosedCaseOne {
            get {
                return ResourceManager.GetString("ClosedCaseOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلقة 2.
        /// </summary>
        public static string ClosedCaseTwo {
            get {
                return ResourceManager.GetString("ClosedCaseTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة او مؤسسة.
        /// </summary>
        public static string CompanyOrInstitution {
            get {
                return ResourceManager.GetString("CompanyOrInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرية.
        /// </summary>
        public static string Confidential {
            get {
                return ResourceManager.GetString("Confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعيين استشارى.
        /// </summary>
        public static string ConsultantAssigned {
            get {
                return ResourceManager.GetString("ConsultantAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب نواقص.
        /// </summary>
        public static string ConsultationSupportingDocument {
            get {
                return ResourceManager.GetString("ConsultationSupportingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبول النموذج.
        /// </summary>
        public static string ConsultationTransactionTypes_Accepted {
            get {
                return ResourceManager.GetString("ConsultationTransactionTypes.Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتماد النموذج.
        /// </summary>
        public static string ConsultationTransactionTypes_Approved {
            get {
                return ResourceManager.GetString("ConsultationTransactionTypes.Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء النموذج.
        /// </summary>
        public static string ConsultationTransactionTypes_Created {
            get {
                return ResourceManager.GetString("ConsultationTransactionTypes.Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تسويد النموذج.
        /// </summary>
        public static string ConsultationTransactionTypes_Drafted {
            get {
                return ResourceManager.GetString("ConsultationTransactionTypes.Drafted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصدير النموذج.
        /// </summary>
        public static string ConsultationTransactionTypes_Exported {
            get {
                return ResourceManager.GetString("ConsultationTransactionTypes.Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل النموذج.
        /// </summary>
        public static string ConsultationTransactionTypes_Modified {
            get {
                return ResourceManager.GetString("ConsultationTransactionTypes.Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة النموذج.
        /// </summary>
        public static string ConsultationTransactionTypes_Returned {
            get {
                return ResourceManager.GetString("ConsultationTransactionTypes.Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء قضية تالية.
        /// </summary>
        public static string CreateNextCase {
            get {
                return ResourceManager.GetString("CreateNextCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انشاء الطلب.
        /// </summary>
        public static string CreateRequest {
            get {
                return ResourceManager.GetString("CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدعى عليها.
        /// </summary>
        public static string Defendant {
            get {
                return ResourceManager.GetString("Defendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محذوفة.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم النطق بحكم الاستئناف.
        /// </summary>
        public static string DoneAppellateJudgment {
            get {
                return ResourceManager.GetString("DoneAppellateJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم النطق بالحكم الابتدائي.
        /// </summary>
        public static string DoneElementaryJudgment {
            get {
                return ResourceManager.GetString("DoneElementaryJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم النطق بالحكم.
        /// </summary>
        public static string DoneJudgment {
            get {
                return ResourceManager.GetString("DoneJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم النطق بحكم العليا.
        /// </summary>
        public static string DoneSupremeJudgment {
            get {
                return ResourceManager.GetString("DoneSupremeJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسودة.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل صك الحكم.
        /// </summary>
        public static string EditReceiveJudmentInstrument {
            get {
                return ResourceManager.GetString("EditReceiveJudmentInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل موعد استلام الحكم.
        /// </summary>
        public static string EditReceivingJudgmentDate {
            get {
                return ResourceManager.GetString("EditReceivingJudgmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعليمي.
        /// </summary>
        public static string Educational {
            get {
                return ResourceManager.GetString("Educational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهاء فترة الاعتراض.
        /// </summary>
        public static string EndOfObjectionPeriod {
            get {
                return ResourceManager.GetString("EndOfObjectionPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التصدير.
        /// </summary>
        public static string Exported {
            get {
                return ResourceManager.GetString("Exported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاشلة.
        /// </summary>
        public static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لصالح الوزارة.
        /// </summary>
        public static string Favor {
            get {
                return ResourceManager.GetString("Favor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهمة ميدانية.
        /// </summary>
        public static string FieldMission {
            get {
                return ResourceManager.GetString("FieldMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحكم النهائى.
        /// </summary>
        public static string FinalJudgment {
            get {
                return ResourceManager.GetString("FinalJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منتهية.
        /// </summary>
        public static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدائية.
        /// </summary>
        public static string FirstInstance {
            get {
                return ResourceManager.GetString("FirstInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة حكومية.
        /// </summary>
        public static string GovernmentalEntity {
            get {
                return ResourceManager.GetString("GovernmentalEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أمين لجنة.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلسة.
        /// </summary>
        public static string Hearing {
            get {
                return ResourceManager.GetString("Hearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنتهاء لإستماع.
        /// </summary>
        public static string HearingClosed {
            get {
                return ResourceManager.GetString("HearingClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدأ الإستماع.
        /// </summary>
        public static string HearingStarted {
            get {
                return ResourceManager.GetString("HearingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث الجلسة.
        /// </summary>
        public static string HearingUpdate {
            get {
                return ResourceManager.GetString("HearingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ديوان المظالم.
        /// </summary>
        public static string HouseOfGrievances {
            get {
                return ResourceManager.GetString("HouseOfGrievances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحدود.
        /// </summary>
        public static string IdentityTypes_Border {
            get {
                return ResourceManager.GetString("IdentityTypes.Border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هوية خليجية.
        /// </summary>
        public static string IdentityTypes_Gulf {
            get {
                return ResourceManager.GetString("IdentityTypes.Gulf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقامة.
        /// </summary>
        public static string IdentityTypes_Iqama {
            get {
                return ResourceManager.GetString("IdentityTypes.Iqama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هوية وطنية.
        /// </summary>
        public static string IdentityTypes_National {
            get {
                return ResourceManager.GetString("IdentityTypes.National", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أخرى.
        /// </summary>
        public static string IdentityTypes_Other {
            get {
                return ResourceManager.GetString("IdentityTypes.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جواز سفر.
        /// </summary>
        public static string IdentityTypes_Passport {
            get {
                return ResourceManager.GetString("IdentityTypes.Passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هوية زائر.
        /// </summary>
        public static string IdentityTypes_Visitor {
            get {
                return ResourceManager.GetString("IdentityTypes.Visitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واردة.
        /// </summary>
        public static string Imported {
            get {
                return ResourceManager.GetString("Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وارد.
        /// </summary>
        public static string Inbound {
            get {
                return ResourceManager.GetString("Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قضية واردة.
        /// </summary>
        public static string IncomingCase {
            get {
                return ResourceManager.GetString("IncomingCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات مكتملة.
        /// </summary>
        public static string InfoCompleted {
            get {
                return ResourceManager.GetString("InfoCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنشائية.
        /// </summary>
        public static string Initiator {
            get {
                return ResourceManager.GetString("Initiator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محضر تحقيق.
        /// </summary>
        public static string InvestigationRecord {
            get {
                return ResourceManager.GetString("InvestigationRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئيسية.
        /// </summary>
        public static string Major {
            get {
                return ResourceManager.GetString("Major", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضو لجنة.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مذكرة.
        /// </summary>
        public static string Memo {
            get {
                return ResourceManager.GetString("Memo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزارة العدل.
        /// </summary>
        public static string MinistryOfJustice {
            get {
                return ResourceManager.GetString("MinistryOfJustice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معاملة.
        /// </summary>
        public static string Moamala {
            get {
                return ResourceManager.GetString("Moamala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معادة.
        /// </summary>
        public static string MoamalaReturned {
            get {
                return ResourceManager.GetString("MoamalaReturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معدل الصياغة.
        /// </summary>
        public static string Modified {
            get {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معين.
        /// </summary>
        public static string Moeen {
            get {
                return ResourceManager.GetString("Moeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناجز.
        /// </summary>
        public static string Najiz {
            get {
                return ResourceManager.GetString("Najiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قضية جديدة.
        /// </summary>
        public static string NewCase {
            get {
                return ResourceManager.GetString("NewCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديدة.
        /// </summary>
        public static string NewMemo {
            get {
                return ResourceManager.GetString("NewMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إكتفاء بالحكم.
        /// </summary>
        public static string NoFutherAction {
            get {
                return ResourceManager.GetString("NoFutherAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عادية.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتراضية.
        /// </summary>
        public static string Objection {
            get {
                return ResourceManager.GetString("Objection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مذكرة اعتراضية على الحكم.
        /// </summary>
        public static string ObjectionLegalMemoRequest {
            get {
                return ResourceManager.GetString("ObjectionLegalMemoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب توجيه بالاعتراض او الاكتفاء بالحكم.
        /// </summary>
        public static string ObjectionPermitRequest {
            get {
                return ResourceManager.GetString("ObjectionPermitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل الاعتراض.
        /// </summary>
        public static string ObjectionRecorded {
            get {
                return ResourceManager.GetString("ObjectionRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to على رأس العمل.
        /// </summary>
        public static string OnTheJob {
            get {
                return ResourceManager.GetString("OnTheJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ممثل جهة.
        /// </summary>
        public static string OrganizationAgent {
            get {
                return ResourceManager.GetString("OrganizationAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صادر.
        /// </summary>
        public static string Outbound {
            get {
                return ResourceManager.GetString("Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أب.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة حكومية.
        /// </summary>
        public static string PartyEntityTypes_Government {
            get {
                return ResourceManager.GetString("PartyEntityTypes.Government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شركة/مؤسسة.
        /// </summary>
        public static string PartyEntityTypes_Organization {
            get {
                return ResourceManager.GetString("PartyEntityTypes.Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرد.
        /// </summary>
        public static string PartyEntityTypes_Person {
            get {
                return ResourceManager.GetString("PartyEntityTypes.Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصالح.
        /// </summary>
        public static string Peace {
            get {
                return ResourceManager.GetString("Peace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرد.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدعى.
        /// </summary>
        public static string Plaintiff {
            get {
                return ResourceManager.GetString("Plaintiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرافعة.
        /// </summary>
        public static string Pleading {
            get {
                return ResourceManager.GetString("Pleading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاص.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إجرائية.
        /// </summary>
        public static string Procedural {
            get {
                return ResourceManager.GetString("Procedural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نطق بالحكم.
        /// </summary>
        public static string PronouncingJudgment {
            get {
                return ResourceManager.GetString("PronouncingJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عام.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لجنة شبه قضائية.
        /// </summary>
        public static string QuasiJudicialCommittee {
            get {
                return ResourceManager.GetString("QuasiJudicialCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لجان شبة قضائية.
        /// </summary>
        public static string QuasiJudicialCommittees {
            get {
                return ResourceManager.GetString("QuasiJudicialCommittees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوع لرئيس اللجان.
        /// </summary>
        public static string RaisingAllBoardsHead {
            get {
                return ResourceManager.GetString("RaisingAllBoardsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوعة للمستشار.
        /// </summary>
        public static string RaisingConsultant {
            get {
                return ResourceManager.GetString("RaisingConsultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محولة إلى لجنة رئيسية.
        /// </summary>
        public static string RaisingMainBoardHead {
            get {
                return ResourceManager.GetString("RaisingMainBoardHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محولة إلى لجنة فرعية.
        /// </summary>
        public static string RaisingSubBoardHead {
            get {
                return ResourceManager.GetString("RaisingSubBoardHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصنفة.
        /// </summary>
        public static string Rated {
            get {
                return ResourceManager.GetString("Rated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام الحكم.
        /// </summary>
        public static string ReceiptJudgment {
            get {
                return ResourceManager.GetString("ReceiptJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستلمة.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستلمة من مدير المنطقة.
        /// </summary>
        public static string ReceivedByBranchManager {
            get {
                return ResourceManager.GetString("ReceivedByBranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستلمة من مدير الترافع.
        /// </summary>
        public static string ReceivedByLitigationManager {
            get {
                return ResourceManager.GetString("ReceivedByLitigationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستلمة من مشرف المناطق.
        /// </summary>
        public static string ReceivedByRegionsSupervisor {
            get {
                return ResourceManager.GetString("ReceivedByRegionsSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مستلمة من الباحث.
        /// </summary>
        public static string ReceivedByResearcher {
            get {
                return ResourceManager.GetString("ReceivedByResearcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام صك الحكم.
        /// </summary>
        public static string ReceiveJudmentInstrument {
            get {
                return ResourceManager.GetString("ReceiveJudmentInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تسجيل طلب اعتراض على الحكم.
        /// </summary>
        public static string RecordObjectionRequest {
            get {
                return ResourceManager.GetString("RecordObjectionRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطوي القيد.
        /// </summary>
        public static string RecordPleated {
            get {
                return ResourceManager.GetString("RecordPleated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم استلام تاريخ الحكم.
        /// </summary>
        public static string RecordReceivingJudgmentDate {
            get {
                return ResourceManager.GetString("RecordReceivingJudgmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محالة.
        /// </summary>
        public static string Referred {
            get {
                return ResourceManager.GetString("Referred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفض طلب تغيير الباحث.
        /// </summary>
        public static string RejectChangeResearcherRequest {
            get {
                return ResourceManager.GetString("RejectChangeResearcherRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرفوض.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف بيانات استلام الحكم.
        /// </summary>
        public static string RemoveReceivingJudgmentDate {
            get {
                return ResourceManager.GetString("RemoveReceivingJudgmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعة طلب مذكرة اعتراضية.
        /// </summary>
        public static string ReplyObjectionLegalMemoRequest {
            get {
                return ResourceManager.GetString("ReplyObjectionLegalMemoRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعة طلب الاعتراض او الاكتفاء بالحكم.
        /// </summary>
        public static string ReplyObjectionPermitRequest {
            get {
                return ResourceManager.GetString("ReplyObjectionPermitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة خطاب التمثيل.
        /// </summary>
        public static string RepresentativeLetterImage {
            get {
                return ResourceManager.GetString("RepresentativeLetterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشرف العام على الادارة العامة للشئون القانونية.
        /// </summary>
        public static string RepresentativeLetterSources_GeneralSupervisor {
            get {
                return ResourceManager.GetString("RepresentativeLetterSources.GeneralSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موقوف.
        /// </summary>
        public static string Request_Abandoned {
            get {
                return ResourceManager.GetString("Request.Abandoned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقبول.
        /// </summary>
        public static string Request_Accepted {
            get {
                return ResourceManager.GetString("Request.Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقبول من مدير الترافع.
        /// </summary>
        public static string Request_AcceptedFromLitigationManager {
            get {
                return ResourceManager.GetString("Request.AcceptedFromLitigationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معتمد.
        /// </summary>
        public static string Request_Approved {
            get {
                return ResourceManager.GetString("Request.Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملغي.
        /// </summary>
        public static string Request_Canceled {
            get {
                return ResourceManager.GetString("Request.Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إنشاء القضية.
        /// </summary>
        public static string Request_CaseCreation {
            get {
                return ResourceManager.GetString("Request.CaseCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        public static string Request_Closed {
            get {
                return ResourceManager.GetString("Request.Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبول الطلب.
        /// </summary>
        public static string RequestAccepted {
            get {
                return ResourceManager.GetString("RequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة مذكرة لجلسة.
        /// </summary>
        public static string RequestAddHearingMemo {
            get {
                return ResourceManager.GetString("RequestAddHearingMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب خطاب إلحاقى.
        /// </summary>
        public static string RequestAttachedLetter {
            get {
                return ResourceManager.GetString("RequestAttachedLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب تصدير الحكم.
        /// </summary>
        public static string RequestExportCaseJudgment {
            get {
                return ResourceManager.GetString("RequestExportCaseJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب اعتراض.
        /// </summary>
        public static string RequestObjection {
            get {
                return ResourceManager.GetString("RequestObjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفض الطلب.
        /// </summary>
        public static string RequestRejected {
            get {
                return ResourceManager.GetString("RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب تغيير باحث.
        /// </summary>
        public static string RequestResearcherChange {
            get {
                return ResourceManager.GetString("RequestResearcherChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب تغيير المكلف بحضور الجلسة.
        /// </summary>
        public static string RequestResearcherChangeToHearing {
            get {
                return ResourceManager.GetString("RequestResearcherChangeToHearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب مستندات داعمة.
        /// </summary>
        public static string RequestSupportingDocuments {
            get {
                return ResourceManager.GetString("RequestSupportingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدعى عليه.
        /// </summary>
        public static string Respondent {
            get {
                return ResourceManager.GetString("Respondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متقاعد.
        /// </summary>
        public static string Retired {
            get {
                return ResourceManager.GetString("Retired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مردود لإعادة الصياغة.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مردود لإعادة الإدخال.
        /// </summary>
        public static string ReturnedToDataEntry {
            get {
                return ResourceManager.GetString("ReturnedToDataEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معادة الى مدير الترافع.
        /// </summary>
        public static string ReturnedToLitigationManager {
            get {
                return ResourceManager.GetString("ReturnedToLitigationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معادة إلى مشرف المناطق.
        /// </summary>
        public static string ReturnedToRegionsSupervisor {
            get {
                return ResourceManager.GetString("ReturnedToRegionsSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة الى مدير الترافع.
        /// </summary>
        public static string ReturnToLitigationManager {
            get {
                return ResourceManager.GetString("ReturnToLitigationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة الى مشرف المناطق.
        /// </summary>
        public static string ReturnToRegionsSupervisor {
            get {
                return ResourceManager.GetString("ReturnToRegionsSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجدولة.
        /// </summary>
        public static string Scheduled {
            get {
                return ResourceManager.GetString("Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرعية.
        /// </summary>
        public static string Secondary {
            get {
                return ResourceManager.GetString("Secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالاصالة عن نفسه.
        /// </summary>
        public static string Self {
            get {
                return ResourceManager.GetString("Self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احالة الى مدير المنطقة.
        /// </summary>
        public static string SendToBranchManager {
            get {
                return ResourceManager.GetString("SendToBranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to احالة الى مشرف المناطق.
        /// </summary>
        public static string SendToRegionsSupervisor {
            get {
                return ResourceManager.GetString("SendToRegionsSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختيار باحث.
        /// </summary>
        public static string SendToResearcher {
            get {
                return ResourceManager.GetString("SendToResearcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واردة إلى مدير المنطقة.
        /// </summary>
        public static string SentToBranchManager {
            get {
                return ResourceManager.GetString("SentToBranchManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واردة إلى مشرف المناطق.
        /// </summary>
        public static string SentToRegionsSupervisor {
            get {
                return ResourceManager.GetString("SentToRegionsSupervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناجحة.
        /// </summary>
        public static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عليا.
        /// </summary>
        public static string Supreme {
            get {
                return ResourceManager.GetString("Supreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهمة.
        /// </summary>
        public static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاب إلحاقى.
        /// </summary>
        public static string Tempalte_AttachedLetter {
            get {
                return ResourceManager.GetString("Tempalte.AttachedLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطاب مستندات داعمه.
        /// </summary>
        public static string Template_CaseSupportingDocumentLetter {
            get {
                return ResourceManager.GetString("Template.CaseSupportingDocumentLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إنهائية.
        /// </summary>
        public static string Terminator {
            get {
                return ResourceManager.GetString("Terminator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معطلة.
        /// </summary>
        public static string Unactivated {
            get {
                return ResourceManager.GetString("Unactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير محدد.
        /// </summary>
        public static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بالانتظار.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
    }
}
