//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moe.La.Common.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Moe.La.Common.Resources.Common.ValidatorsMessages", typeof(ValidatorsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحدث باللغة العربية.
        /// </summary>
        public static string ActionArName {
            get {
                return ResourceManager.GetString("ActionArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحدث باللغة الانجليزية.
        /// </summary>
        public static string ActionEnName {
            get {
                return ResourceManager.GetString("ActionEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل العنوان.
        /// </summary>
        public static string AddressDetails {
            get {
                return ResourceManager.GetString("AddressDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مذكرة الاستئناف.
        /// </summary>
        public static string AppealLegalMemoId {
            get {
                return ResourceManager.GetString("AppealLegalMemoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أسباب الاستئناف.
        /// </summary>
        public static string AppealReasons {
            get {
                return ResourceManager.GetString("AppealReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الملف.
        /// </summary>
        public static string AttachmentType {
            get {
                return ResourceManager.GetString("AttachmentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المحامى.
        /// </summary>
        public static string AttorneyNumber {
            get {
                return ResourceManager.GetString("AttorneyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم اللجنة.
        /// </summary>
        public static string BoardId {
            get {
                return ResourceManager.GetString("BoardId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعضاء اللجنة.
        /// </summary>
        public static string BoardMeetingMembers {
            get {
                return ResourceManager.GetString("BoardMeetingMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم البناية.
        /// </summary>
        public static string BuidlignNumber {
            get {
                return ResourceManager.GetString("BuidlignNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصنيف القضية.
        /// </summary>
        public static string CaseCategories {
            get {
                return ResourceManager.GetString("CaseCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الدعوى.
        /// </summary>
        public static string CaseDescription {
            get {
                return ResourceManager.GetString("CaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القضية.
        /// </summary>
        public static string CaseId {
            get {
                return ResourceManager.GetString("CaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة المعنية بالحكم.
        /// </summary>
        public static string CaseRuleGeneralManagementIds {
            get {
                return ResourceManager.GetString("CaseRuleGeneralManagementIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة المعنية بالحكم.
        /// </summary>
        public static string CaseRuleLegalAffairsDepartmentIds {
            get {
                return ResourceManager.GetString("CaseRuleLegalAffairsDepartmentIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مصدر القضية.
        /// </summary>
        public static string CaseSource {
            get {
                return ResourceManager.GetString("CaseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القضية.
        /// </summary>
        public static string CaseSourceNumber {
            get {
                return ResourceManager.GetString("CaseSourceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CategoryArName {
            get {
                return ResourceManager.GetString("CategoryArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CategoryEnName {
            get {
                return ResourceManager.GetString("CategoryEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الدائرة.
        /// </summary>
        public static string CircleNumber {
            get {
                return ResourceManager.GetString("CircleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        public static string Closed {
            get {
                return ResourceManager.GetString("Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب الاغلاق.
        /// </summary>
        public static string ClosingReason {
            get {
                return ResourceManager.GetString("ClosingReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غلق التقرير.
        /// </summary>
        public static string ClosingReport {
            get {
                return ResourceManager.GetString("ClosingReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القضية في اللجنة.
        /// </summary>
        public static string CommitteeCaseNo {
            get {
                return ResourceManager.GetString("CommitteeCaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة السرية.
        /// </summary>
        public static string ConfidentialDegree {
            get {
                return ResourceManager.GetString("ConfidentialDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الادارة المرسل إليها .
        /// </summary>
        public static string ConsigneeDepartment {
            get {
                return ResourceManager.GetString("ConsigneeDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستشار.
        /// </summary>
        public static string ConsultantId {
            get {
                return ResourceManager.GetString("ConsultantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموضوع.
        /// </summary>
        public static string ConsultationSubject {
            get {
                return ResourceManager.GetString("ConsultationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحكمة.
        /// </summary>
        public static string CourtId {
            get {
                return ResourceManager.GetString("CourtId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف خطوة الحدث.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحليل و الرأي.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الملف.
        /// </summary>
        public static string FileNo {
            get {
                return ResourceManager.GetString("FileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاستنتاجات النهائية.
        /// </summary>
        public static string FinalConclusions {
            get {
                return ResourceManager.GetString("FinalConclusions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأول.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المجموعة.
        /// </summary>
        public static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المجموعة.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الجلسة.
        /// </summary>
        public static string HearingDate {
            get {
                return ResourceManager.GetString("HearingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجلسة.
        /// </summary>
        public static string HearingId {
            get {
                return ResourceManager.GetString("HearingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجلسة.
        /// </summary>
        public static string HearingNumber {
            get {
                return ResourceManager.GetString("HearingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الجلسة.
        /// </summary>
        public static string HearingTime {
            get {
                return ResourceManager.GetString("HearingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهوية او الاقامة.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المصدر التعريفيى.
        /// </summary>
        public static string IdentitySource {
            get {
                return ResourceManager.GetString("IdentitySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة التعريفية.
        /// </summary>
        public static string IdentityValue {
            get {
                return ResourceManager.GetString("IdentityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القضية.
        /// </summary>
        public static string InitialCaseId {
            get {
                return ResourceManager.GetString("InitialCaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون اكبر من الصفر.
        /// </summary>
        public static string InValid {
            get {
                return ResourceManager.GetString("InValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مغلق.
        /// </summary>
        public static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حكم نهائي.
        /// </summary>
        public static string IsFinalJudgment {
            get {
                return ResourceManager.GetString("IsFinalJudgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الايزو.
        /// </summary>
        public static string ISO31661CodeAlph3 {
            get {
                return ResourceManager.GetString("ISO31661CodeAlph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقروء.
        /// </summary>
        public static string IsRead {
            get {
                return ResourceManager.GetString("IsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحكم.
        /// </summary>
        public static string JudgementResult {
            get {
                return ResourceManager.GetString("JudgementResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص الحكم.
        /// </summary>
        public static string JudgementText {
            get {
                return ResourceManager.GetString("JudgementText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم القضية.
        /// </summary>
        public static string JudgeName {
            get {
                return ResourceManager.GetString("JudgeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مختصر الحكم.
        /// </summary>
        public static string JudgmentBrief {
            get {
                return ResourceManager.GetString("JudgmentBrief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملخص صك الحكم.
        /// </summary>
        public static string JudgmentInstrumentSummary {
            get {
                return ResourceManager.GetString("JudgmentInstrumentSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسباب التى بني عليها الحكم.
        /// </summary>
        public static string JudgmentReasons {
            get {
                return ResourceManager.GetString("JudgmentReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم الأخير.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحليل القانوني.
        /// </summary>
        public static string LegalAnalysis {
            get {
                return ResourceManager.GetString("LegalAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المذكرة.
        /// </summary>
        public static string LegalMemoId {
            get {
                return ResourceManager.GetString("LegalMemoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفة الوزارة القانونية.
        /// </summary>
        public static string LegalStatus {
            get {
                return ResourceManager.GetString("LegalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخطاب.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درجة الترافع.
        /// </summary>
        public static string LitigationType {
            get {
                return ResourceManager.GetString("LitigationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة الاغلاق.
        /// </summary>
        public static string LockPeriod {
            get {
                return ResourceManager.GetString("LockPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الرئيسي.
        /// </summary>
        public static string MainNo {
            get {
                return ResourceManager.GetString("MainNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعدى عدد الاحرف المطلوبة.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وقت الاجتماع.
        /// </summary>
        public static string MeetingDate {
            get {
                return ResourceManager.GetString("MeetingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مكان الاجتماع.
        /// </summary>
        public static string MeetingPlace {
            get {
                return ResourceManager.GetString("MeetingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المذكرة.
        /// </summary>
        public static string MemoId {
            get {
                return ResourceManager.GetString("MemoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة.
        /// </summary>
        public static string MoamalaId {
            get {
                return ResourceManager.GetString("MoamalaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة.
        /// </summary>
        public static string MoamalaNumber {
            get {
                return ResourceManager.GetString("MoamalaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإدارة الداخلية أو الجهة الخارجية المرسلة للمعاملة.
        /// </summary>
        public static string MoamlaDepartmentId {
            get {
                return ResourceManager.GetString("MoamlaDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفاصيل المعاملة.
        /// </summary>
        public static string MoamlaDescription {
            get {
                return ResourceManager.GetString("MoamlaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة المعاملة.
        /// </summary>
        public static string MoamlaStatus {
            get {
                return ResourceManager.GetString("MoamlaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان المعاملة.
        /// </summary>
        public static string MoamlaSubject {
            get {
                return ResourceManager.GetString("MoamlaSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الجوال.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الدعوى في معين.
        /// </summary>
        public static string MoeenId {
            get {
                return ResourceManager.GetString("MoeenId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة في معين.
        /// </summary>
        public static string MoeenRef {
            get {
                return ResourceManager.GetString("MoeenRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات.
        /// </summary>
        public static string Motions {
            get {
                return ResourceManager.GetString("Motions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القضية في ناجز.
        /// </summary>
        public static string NajizCaseNo {
            get {
                return ResourceManager.GetString("NajizCaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب في ناجز.
        /// </summary>
        public static string NajizId {
            get {
                return ResourceManager.GetString("NajizId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المعاملة في ناجز.
        /// </summary>
        public static string NajizRef {
            get {
                return ResourceManager.GetString("NajizRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأسم.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم باللغة العربية.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم باللغة الانجليزية.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية باللغة العربية.
        /// </summary>
        public static string NationalityAr {
            get {
                return ResourceManager.GetString("NationalityAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية باللغة الانجليزية.
        /// </summary>
        public static string NationalityEn {
            get {
                return ResourceManager.GetString("NationalityEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملاحظات.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الاشعار.
        /// </summary>
        public static string NotificationType {
            get {
                return ResourceManager.GetString("NotificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم طلب الاعتراض للحكم.
        /// </summary>
        public static string ObjectionRequestId {
            get {
                return ResourceManager.GetString("ObjectionRequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلبات المقدمة فى الطلب.
        /// </summary>
        public static string ObjectionRequestRequests {
            get {
                return ResourceManager.GetString("ObjectionRequestRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع طلب الاعتراض.
        /// </summary>
        public static string ObjectionRequestType {
            get {
                return ResourceManager.GetString("ObjectionRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الطلب.
        /// </summary>
        public static string OrderDescription {
            get {
                return ResourceManager.GetString("OrderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطرف.
        /// </summary>
        public static string PartyId {
            get {
                return ResourceManager.GetString("PartyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الرابط.
        /// </summary>
        public static string PartyPresentation {
            get {
                return ResourceManager.GetString("PartyPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ ووقت المرور.
        /// </summary>
        public static string PassDate {
            get {
                return ResourceManager.GetString("PassDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المرور واردة ام صادرة.
        /// </summary>
        public static string PassType {
            get {
                return ResourceManager.GetString("PassType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم البريدى.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطوق الحكم.
        /// </summary>
        public static string PronouncedJudgmentText {
            get {
                return ResourceManager.GetString("PronouncedJudgmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النطق بالحكم.
        /// </summary>
        public static string PronouncingJudgmentDate {
            get {
                return ResourceManager.GetString("PronouncingJudgmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نص السؤال.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القيد في راسل.
        /// </summary>
        public static string RaselRef {
            get {
                return ResourceManager.GetString("RaselRef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الموحد في راسل.
        /// </summary>
        public static string RaselUnifiedNo {
            get {
                return ResourceManager.GetString("RaselUnifiedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ موعد استلام الحكم.
        /// </summary>
        public static string ReceivingJudgmentDate {
            get {
                return ResourceManager.GetString("ReceivingJudgmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم القضية المرجعية.
        /// </summary>
        public static string ReferenceCaseNo {
            get {
                return ResourceManager.GetString("ReferenceCaseNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القضية الاساسية.
        /// </summary>
        public static string RelatedCaseId {
            get {
                return ResourceManager.GetString("RelatedCaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات الطلب.
        /// </summary>
        public static string ReplyNote {
            get {
                return ResourceManager.GetString("ReplyNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورة خطاب التمثيل.
        /// </summary>
        public static string RepresentativeLetterImage {
            get {
                return ResourceManager.GetString("RepresentativeLetterImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم خطاب التمثيل.
        /// </summary>
        public static string RepresentativeLetterNumber {
            get {
                return ResourceManager.GetString("RepresentativeLetterNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الطلب.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الطلب.
        /// </summary>
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الطلب.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مطلوب.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إضافة باحث واحد على الاقل.
        /// </summary>
        public static string ResearchCountRequired {
            get {
                return ResourceManager.GetString("ResearchCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباحث.
        /// </summary>
        public static string ResearcherId {
            get {
                return ResourceManager.GetString("ResearcherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الباحث.
        /// </summary>
        public static string ResourceId {
            get {
                return ResourceManager.GetString("ResourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المراجعة.
        /// </summary>
        public static string ReviewNumber {
            get {
                return ResourceManager.GetString("ReviewNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الوظيفة.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف الفرعي.
        /// </summary>
        public static string SecondSubCategory {
            get {
                return ResourceManager.GetString("SecondSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محضر الجلسة.
        /// </summary>
        public static string SessionMinutes {
            get {
                return ResourceManager.GetString("SessionMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بداية القضية.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة القضية.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحالة باللغة العربية.
        /// </summary>
        public static string StatusArName {
            get {
                return ResourceManager.GetString("StatusArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الحالة باللغة الانجليزية.
        /// </summary>
        public static string StatusEnName {
            get {
                return ResourceManager.GetString("StatusEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحالة.
        /// </summary>
        public static string StatusId {
            get {
                return ResourceManager.GetString("StatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الخطوة باللغة العربية.
        /// </summary>
        public static string StepArName {
            get {
                return ResourceManager.GetString("StepArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الخطوة باللغة الانجليزية.
        /// </summary>
        public static string StepEnName {
            get {
                return ResourceManager.GetString("StepEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الشارع.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الدعوى.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملخص الجلسة.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string TelephoneNumber {
            get {
                return ResourceManager.GetString("TelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النص.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المستخدم المرسل اليه.
        /// </summary>
        public static string ToUserId {
            get {
                return ResourceManager.GetString("ToUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الحركة.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم النوع باللغة العربية.
        /// </summary>
        public static string TypeArName {
            get {
                return ResourceManager.GetString("TypeArName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم النوع باللغة الانجليزية.
        /// </summary>
        public static string TypeEnName {
            get {
                return ResourceManager.GetString("TypeEnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم النوع.
        /// </summary>
        public static string TypeId {
            get {
                return ResourceManager.GetString("TypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الموحد او المرجعى للمعاملة.
        /// </summary>
        public static string UnifiedNo {
            get {
                return ResourceManager.GetString("UnifiedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرابط.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
